language: go
sudo: required
go: 
  - 1.13
install: true

before_script:
  - mkdir -p $HOME/gopath/src/github.com/yankooo/go-archaius
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/yankooo/go-archaius/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/yankooo/go-archaius
  - cd $HOME/gopath/src/github.com/yankooo/go-archaius
jobs:
  include:
    - stage: Format Checker
      script: bash scripts/travis/formatChecker.sh
    - stage: DeadCode Checker
      script: 
        - go get -u github.com/tsenart/deadcode
        - bash scripts/travis/deadCodeChecker.sh
    - stage: Misspell Checker
      script: 
        - go get -u github.com/client9/misspell
        - bash scripts/travis/misspellChecker.sh
    - stage: GoConst Checker
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash scripts/travis/goConstChecker.sh
    - stage: GoLint Checker
      script:
        - go get -u golang.org/x/lint/golint
        - bash scripts/travis/goLintChecker.sh
    - stage: GoCyclo Checker
      script:
        - go get github.com/fzipp/gocyclo
        - bash scripts/travis/goCycloChecker.sh
    - stage: Unit Test
      script:
        - GO111MODULE=on go mod download
        - GO111MODULE=on go mod vendor
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - bash scripts/travis/unit_test.sh

